### ISSUE TITLE
Top level Java package is wrong

### ISSUE THREAD

**Issue by johntopleyons** [ONSdigital/florence#3]
Your top level Java package is wrong. It should be `uk.gov.ons` rather than `com.github`! From https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

> Companies use their reversed Internet domain name to begin their package names—for example, com.example.mypackage for a package named mypackage created by a programmer at example.com.

**Comment by ian-kent** [comment]
Closing since we no longer use Java 😸
